apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone-cluster-prod
  region: us-east-1

managedNodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 3
    volumeSize: 20
    maxSize: 4
    minSize: 2
    ssh:
      publicKeyName: nd0044_key_pair
    
availabilityZones: ['us-east-1a', 'us-east-1b', 'us-east-1c', 'us-east-1d']