apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone
        image: 415235275749.dkr.ecr.us-east-1.amazonaws.com/capstone:$(CIRCLE_WORKFLOW_ID) 
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: capstone
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: capstone